### ISSUE TITLE
Unable to locate the entry point

### ISSUE THREAD

**Issue by dogboydog** [ui-js/grok#17]
Hi, this doc generator looks cool and I would like to try it out. However, I am not able to get it to generate anything with a single index.d.ts file in my dist/ folder, and I also cloned this project and tried to generate the doc from the `test` directory and received the same error: 
```bash
$ grok ./test/ --outDir docs
Unable to locate entry point: C:/Users/chris/Documents/grok/test
Unable to find any entry points. Make sure TypeDoc can find your tsconfig
```
Here's the other project dir I tried to use: 

![image](https://user-images.githubusercontent.com/9920963/224118315-2b78a3cf-25f2-4932-916a-c2046dcc1c54.png)

After getting the above error I tried to add a tsconfig.json in the `dist` directory, but that just caused a different error 
```
$ npx grok ./dist --outDir docs
Unable to locate entry point: C:/Users/chris/Documents/tiled-doc/dist
Unable to find any entry points. Make sure TypeDoc can find your tsconfig
Modules index.d.ts not found in "dist"
TypeError: Cannot read properties of undefined (reading 'length')
    at grok (C:\Users\chris\Documents\tiled-doc\node_modules\@ui-js\grok\bin\grok-cli.js:1892:27)
    at Object.build [as handler] (C:\Users\chris\Documents\tiled-doc\node_modules\@ui-js\grok\bin\grok-cli.js:2280:44)
    at C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:8993
    at j (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:9604)
    at _.runCommand (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:7231)
    at [runYargsParserAndExecuteCommands] (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:58917)
    at te.parse (C:\Users\chris\Documents\tiled-doc\node_modules\yargs\build\index.cjs:1:40483)
    at Object.<anonymous> (C:\Users\chris\Documents\tiled-doc\node_modules\@ui-js\grok\bin\grok-cli.js:2322:137)
```
Is there some requirement I'm missing to use this? I only have a single index.d.ts file for my project and no .ts or .js files. Didn't see a mention of tsconfig in the README
    
Thank you

**Comment by dogboydog** [comment]
I was able to generate the doc by making a .tsconfig file as follows: 
```json
{
    "compilerOptions": {
      "declaration": true,
      "emitDecoratorMetadata": false,
      "esModuleInterop": true,
      "experimentalDecorators": false,
      "incremental": true,
      "lib": ["es2020"],
      "module": "es2020",
      "moduleResolution": "node",
      "noImplicitAny": false,
      "noLib": false,
      "removeComments": false,
      "sourceMap": true,
      "strictNullChecks": true,
      "target": "es2020",
      "types": []
    },
    "include": ["index.d.ts"]
  }
  ```

**Comment by arnog** [comment]
Thanks, I've updated the README file accordingly.
