### ISSUE TITLE
 grok ./dist --outDir docs

### ISSUE THREAD

**Issue by physedo** [ui-js/grok#2]
I get this error now

`(base) ai@physedo:~/project$ grok ./dist --outDir docs
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module './package.json'
Require stack:
- /home/ai/.nvm/versions/node/v12.18.1/lib/node_modules/@ui-js/grok/bin/grok-cli
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ai/.nvm/versions/node/v12.18.1/lib/node_modules/@ui-js/grok/bin/grok-cli:2:24303)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ai/.nvm/versions/node/v12.18.1/lib/node_modules/@ui-js/grok/bin/grok-cli'
  ]
}`

**Comment by arnog** [comment]
Arg...
OK, new attempt in 1.0.3...

**Comment by physedo** [comment]
> Arg...
> OK, new attempt in 1.0.3...

works now

**Comment by arnog** [comment]
Phew...
